### PR TITLE
Basic/Concept Logo

### PR DESCRIPTION
**Pull request by ghost**
something i threw together, i have a bunch of ideas in my head and will work on them. currently supposed to be a minimalistic design of kratos from god of war.

### CODE REVIEW

**Comment by khsunny786** [comment]
asen, shut the fuck up

**Comment by ashenasen** [comment]
ur a slut sunny

**Comment by Kyu** [comment]
working on this

**Comment by ashenasen** [comment]
no me

**Comment by H3H3PRODUCTIONS** [comment]
lets give this bot a jewish name like Betzalel

**Comment by ashenasen** [comment]
no thanks

**Comment by ashenasen** [comment]
working on shit thank you ignore this

**Comment by MarkusGordathian** [comment]
Can you guys keep this cancer in the Discord server please.

**Comment by ashenasen** [comment]
ur a slut mark

**Pull request closed without merging**
